name: Python CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Simulando Deploy
      run: |
        echo "Fazendo deploy da Calculadora..."
        echo "App instalado com sucesso no ambiente de producao!"