name: CI/CD Pipeline with Alerts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: |
        # Simulando, criando testes reais
        echo "Executando testes unitários..."

    - name: Discord Notification Success
      if: success()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        details: 'Sua pipeline passou com sucesso!!'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    - name: Discord Notification Failure
      if: failure()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        details: 'O pipeline falhou!'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Simulando Deploy
      run: echo "Deploy realizado com sucesso!"